# Generated by Django 3.0.4 on 2020-03-05 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20200305_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationRecord',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='demo.Vehicle')),
            ],
            options={
                'db_table': 'navigation_records',
            },
        ),
    ]
