# Generated by Django 3.0.4 on 2020-03-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_navigationrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='name',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(default='00ABC000', max_length=8),
            preserve_default=False,
        ),
    ]
